"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-11

Hand-written (not autogenerated -- no live Postgres instance was available
in this environment to diff against; see README "Database & migrations").
Mirrors backend/models/*.py exactly. Verify with `alembic check` once a
Postgres instance is reachable, before relying on this in production.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

CONSUMED_STATUSES_SQL = "status IN ('RESERVED', 'SCHEDULED', 'PUBLISHED')"


def upgrade() -> None:
    op.create_table(
        "accounts",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("username", sa.String(255), nullable=False),
        sa.Column("ig_business_id", sa.String(64), nullable=True),
        sa.Column("page_id", sa.String(64), nullable=True),
        sa.Column("timezone", sa.String(64), nullable=False, server_default="UTC"),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "PAUSED", "DISABLED", name="account_status"),
            nullable=False,
            server_default="ACTIVE",
        ),
        sa.Column(
            "connection_status",
            sa.Enum("CONNECTED", "TOKEN_EXPIRING", "TOKEN_EXPIRED", "DISCONNECTED", "ERROR", name="connection_status"),
            nullable=False,
            server_default="DISCONNECTED",
        ),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("daily_min_posts", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("daily_max_posts", sa.Integer(), nullable=False, server_default="5"),
        sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.create_index("ix_accounts_username", "accounts", ["username"], unique=True)
    op.create_index("ix_accounts_ig_business_id", "accounts", ["ig_business_id"], unique=True)

    op.create_table(
        "account_connections",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("account_id", sa.Uuid(), sa.ForeignKey("accounts.id", ondelete="CASCADE"), nullable=False),
        sa.Column("access_token_encrypted", sa.String(), nullable=False),
        sa.Column("token_type", sa.String(32), nullable=False, server_default="long_lived"),
        sa.Column("refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_account_connections_account_id", "account_connections", ["account_id"])

    op.create_table(
        "masters",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("master_code", sa.String(64), nullable=False),
        sa.Column("filename", sa.String(512), nullable=False),
        sa.Column("filepath", sa.String(1024), nullable=False),
        sa.Column("sha256", sa.String(64), nullable=False),
        sa.Column("perceptual_hash", sa.String(128), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("IMPORTED", "PROCESSING", "READY", "FAILED", name="master_status"),
            nullable=False,
            server_default="IMPORTED",
        ),
    )
    op.create_index("ix_masters_master_code", "masters", ["master_code"], unique=True)
    op.create_index("ix_masters_sha256", "masters", ["sha256"], unique=True)

    op.create_table(
        "variants",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("master_id", sa.Uuid(), sa.ForeignKey("masters.id", ondelete="CASCADE"), nullable=False),
        sa.Column("variant_code", sa.String(96), nullable=False),
        sa.Column("filename", sa.String(512), nullable=False),
        sa.Column("filepath", sa.String(1024), nullable=False),
        sa.Column("sha256", sa.String(64), nullable=False),
        sa.Column("perceptual_hash", sa.String(128), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("transform", sa.String(64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "AVAILABLE", "MISSING_CAPTION", "RESERVED", "SCHEDULED", "PUBLISHED", "FAILED", name="variant_status"
            ),
            nullable=False,
            server_default="AVAILABLE",
        ),
    )
    op.create_index("ix_variants_master_id", "variants", ["master_id"])
    op.create_index("ix_variants_variant_code", "variants", ["variant_code"], unique=True)
    op.create_index("ix_variants_sha256", "variants", ["sha256"], unique=True)
    op.create_index("ix_variants_perceptual_hash", "variants", ["perceptual_hash"])
    op.create_index("ix_variants_status", "variants", ["status"])
    op.create_index("ix_variants_master_status", "variants", ["master_id", "status"])

    op.create_table(
        "captions",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("variant_id", sa.Uuid(), sa.ForeignKey("variants.id", ondelete="CASCADE"), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("source", sa.String(16), nullable=False, server_default="csv"),
    )
    op.create_index("ix_captions_variant_id", "captions", ["variant_id"], unique=True)

    op.create_table(
        "calendar_plans",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "REVIEW", "APPROVED", "ACTIVE", "COMPLETED", "CANCELLED", name="calendar_plan_status"),
            nullable=False,
            server_default="DRAFT",
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("params", sa.JSON(), nullable=True),
    )
    op.create_index("ix_calendar_plans_status", "calendar_plans", ["status"])

    op.create_table(
        "scheduled_posts",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("variant_id", sa.Uuid(), sa.ForeignKey("variants.id", ondelete="RESTRICT"), nullable=False),
        sa.Column("account_id", sa.Uuid(), sa.ForeignKey("accounts.id", ondelete="RESTRICT"), nullable=False),
        sa.Column("master_id", sa.Uuid(), sa.ForeignKey("masters.id", ondelete="RESTRICT"), nullable=False),
        sa.Column(
            "calendar_plan_id", sa.Uuid(), sa.ForeignKey("calendar_plans.id", ondelete="SET NULL"), nullable=True
        ),
        sa.Column("scheduled_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("RESERVED", "SCHEDULED", "PUBLISHED", "FAILED", "CANCELLED", name="scheduled_post_status"),
            nullable=False,
            server_default="RESERVED",
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_post_id", sa.String(128), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_index("ix_scheduled_posts_variant_id", "scheduled_posts", ["variant_id"])
    op.create_index("ix_scheduled_posts_account_id", "scheduled_posts", ["account_id"])
    op.create_index("ix_scheduled_posts_master_id", "scheduled_posts", ["master_id"])
    op.create_index("ix_scheduled_posts_calendar_plan_id", "scheduled_posts", ["calendar_plan_id"])
    op.create_index("ix_scheduled_posts_scheduled_at_utc", "scheduled_posts", ["scheduled_at_utc"])
    op.create_index("ix_scheduled_posts_status", "scheduled_posts", ["status"])
    op.create_index(
        "ix_scheduled_posts_account_master_time", "scheduled_posts", ["account_id", "master_id", "scheduled_at_utc"]
    )
    op.create_index("ix_scheduled_posts_account_time", "scheduled_posts", ["account_id", "scheduled_at_utc"])

    # THE core uniqueness guarantee (§2, §15, §56): only one "consumed"
    # scheduled_posts row may ever exist per variant_id. Postgres and SQLite
    # both support partial unique indexes; this is what makes Test 7 (§48,
    # concurrent double-reservation) provably fail on the loser.
    op.create_index(
        "uq_scheduled_posts_variant_consumed",
        "scheduled_posts",
        ["variant_id"],
        unique=True,
        postgresql_where=sa.text(CONSUMED_STATUSES_SQL),
        sqlite_where=sa.text(CONSUMED_STATUSES_SQL),
    )

    op.create_table(
        "publishing_jobs",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "scheduled_post_id", sa.Uuid(), sa.ForeignKey("scheduled_posts.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("idempotency_key", sa.String(512), nullable=False),
        sa.Column(
            "status",
            sa.Enum("QUEUED", "UPLOADING", "SCHEDULED", "PUBLISHED", "FAILED", "RETRYING", name="publishing_job_status"),
            nullable=False,
            server_default="QUEUED",
        ),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_error", sa.Text(), nullable=True),
    )
    op.create_index("ix_publishing_jobs_scheduled_post_id", "publishing_jobs", ["scheduled_post_id"])
    op.create_index("ix_publishing_jobs_idempotency_key", "publishing_jobs", ["idempotency_key"], unique=True)
    op.create_index("ix_publishing_jobs_status", "publishing_jobs", ["status"])

    op.create_table(
        "publishing_events",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("job_id", sa.Uuid(), sa.ForeignKey("publishing_jobs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("event_type", sa.String(64), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
    )
    op.create_index("ix_publishing_events_job_id", "publishing_events", ["job_id"])

    op.create_table(
        "settings",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("key", sa.String(128), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
    )
    op.create_index("ix_settings_key", "settings", ["key"], unique=True)

    op.create_table(
        "logs",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("level", sa.String(16), nullable=False, server_default="INFO"),
        sa.Column("code", sa.String(64), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("context", sa.JSON(), nullable=True),
    )
    op.create_index("ix_logs_code", "logs", ["code"])


def downgrade() -> None:
    op.drop_table("logs")
    op.drop_table("settings")
    op.drop_table("publishing_events")
    op.drop_table("publishing_jobs")
    op.drop_index("uq_scheduled_posts_variant_consumed", table_name="scheduled_posts")
    op.drop_table("scheduled_posts")
    op.drop_table("calendar_plans")
    op.drop_table("captions")
    op.drop_table("variants")
    op.drop_table("masters")
    op.drop_table("account_connections")
    op.drop_table("accounts")
    for enum_name in (
        "publishing_job_status",
        "scheduled_post_status",
        "calendar_plan_status",
        "variant_status",
        "master_status",
        "connection_status",
        "account_status",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
